# app/config/security.yml

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        UserBundle\Entity\User: sha512
        

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory:
            memory:
                users:
                    admin: {password : admin, roles: ROLE_ADMIN}
        fos_userbundle:
            id: fos_user.user_provider.username

        main:
            id: fos_user.user_provider.username

        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        back:
            pattern: ^/back
            anonymous: ~
            http_basic:
                realm: "Connectez vous !"
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
        # Cette expression régulière permet de prendre /login (mais pas /login_check !)
            pattern:   ^/login$
            anonymous: true # On autorise alors les anonymes sur ce pare-feu
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                
                
            logout:
                path:       fos_user_security_logout
                target: /h
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml

    access_control:
        - { path: ^/admin, ip: 127.0.0.1, requires_channel: https }
        - { path: ^/back/, role: ROLE_ADMIN }